# docker-compose.yml
# 
# Ce fichier configure les services Docker pour l'application ft_transcendence.
# Il définit trois services : frontend, backend et nginx-proxy pour le HTTPS.

version: '3.8'

services:
  # Service frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - frontend-node-modules:/app/node_modules

  # Service backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
    volumes:
      - ./backend/data:/app/data
      - backend-node-modules:/app/node_modules
    networks:
      - app-network

  # Service nginx-proxy pour le HTTPS
  nginx-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

# Définition des volumes
volumes:
  frontend-node-modules:
  backend-node-modules:

# Définition des réseaux
networks:
  app-network:
    driver: bridge
