# docker-compose.yml
# 
# Ce fichier configure les services Docker pour l'application ft_transcendence.
# Il définit deux services : frontend et backend.

version: '3.8'

services:
  # Service frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - frontend-node-modules:/app/node_modules
    ports:
      - "443:3000"

  # Service backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
    volumes:
      - ./backend/data:/app/data
      - backend-node-modules:/app/node_modules
    networks:
      - app-network

# Définition des volumes
volumes:
  frontend-node-modules:
  backend-node-modules:

# Définition des réseaux
networks:
  app-network:
    driver: bridge
